### ISSUE TITLE
TypeError: Argument 0 must be a string

### ISSUE THREAD

**Issue by beyoung** [bjornreppen/rasterize-vector-tiles#1]
could u please detail node version?
my node version is 
**v11.13.0**
and npm version is
**6.7.0**

when I run 
```shell
node rasterize-vector-tiles.js world.mbtiles world-raster.mbtiles --colorprop value --nodata 255
```

It output get 
```
Creating 'undefined'
Reading 'undefined'
Open undefined
TypeError: Argument 0 must be a string
    at Promise (/Users/youngtwain/project/xingzhe/rasterize-vector-tiles/mbtiles/sqlite/sqlite.js:35:16)
    at new Promise (<anonymous>)
    at dball (/Users/youngtwain/project/xingzhe/rasterize-vector-tiles/mbtiles/sqlite/sqlite.js:34:10)
    at listFiles (/Users/youngtwain/project/xingzhe/rasterize-vector-tiles/mbtiles/mbtileReader.js:26:19)
    at readSource (/Users/youngtwain/project/xingzhe/rasterize-vector-tiles/rasterize-vector-tiles.js:75:24)
    at convert (/Users/youngtwain/project/xingzhe/rasterize-vector-tiles/rasterize-vector-tiles.js:99:24)
    at Object.<anonymous> (/Users/youngtwain/project/xingzhe/rasterize-vector-tiles/rasterize-vector-tiles.js:108:1)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
```
so i doubt it's my node version not equal to yours

**Comment by bjornreppen** [comment]
Apologies for poor input argument error handling.  

Improved error handling and messages.  Command line must be in format -i infile -o outfile, not only infile outfile.  

Working command line:
```
node rasterize-vector-tiles.js -i world.mbtiles -o world-raster.mbtiles --colorprop value --nodata 255
```
