### ISSUE TITLE
Cannot export to png files

### ISSUE THREAD

**Issue by hjrobinson** [bjornreppen/rasterize-vector-tiles#3]
I'm trying to use the --png option.  I ran the command below:

 node rasterize-vector-tiles.js -i rasterize-vector-parcels.mbtiles -o rasterize-vector-parcels --colorprop value --nodata 255 --png

But this resulted in an error:

Creating 'rasterize-vector-parcels'
Reading 'rasterize-vector-parcels.mbtiles'
Open rasterize-vector-parcels.mbtiles
Rasterizing zoom level 14
Open rasterize-vector-parcels.mbtiles
Source tile count: 23
Error: ENOENT: no such file or directory, mkdir 'C:\inetpub\wwwroot\assets\rasterize-vector-tiles-master\rasterize-vector-parcels\14\2610'
    at Object.fs.mkdirSync (fs.js:885:18)
    at PngFiles.createTile (C:\inetpub\wwwroot\assets\rasterize-vector-tiles-master\target\pngfiles.js:13:8)
    at rasterizeTile (C:\inetpub\wwwroot\assets\rasterize-vector-tiles-master\rasterize-vector-tiles.js:94:18)
    at rasterize (C:\inetpub\wwwroot\assets\rasterize-vector-tiles-master\rasterize-vector-tiles.js:83:11)
    at convert (C:\inetpub\wwwroot\assets\rasterize-vector-tiles-master\rasterize-vector-tiles.js:105:9)
    at <anonymous>

I also attempted this with a pre-made folder with same name and it still resulted in an error.

**Comment by bjornreppen** [comment]
Are you by any chance using node version lower than 10?  

Seems the code is using a new option that was introduced with node version 10 ```{recursive: true}```
https://stackoverflow.com/questions/31645738/how-to-create-full-path-with-nodes-fs-mkdirsync

 Modified the code to create directory in a backwards compatible way.

**Comment by bjornreppen** [comment]
Thanks for contributing the issue!  Feedback on how to make it more usable appreciated.  Pull requests too.  This project was really kind of a dirty evening hack that I should have given more attention.

**Comment by hjrobinson** [comment]
I'm still getting an error:

$ node rasterize-vector-tiles.js -i rasterize-vector-parcels.mbtiles -o rasterize-vector-parcels --colorprop value --nodata 255 --png

Feature property controlling color: value
Nodata value (ignored features):    255
Constant color for all geometries:  undefined
Antialiasing mode:                  default
Source file:                        rasterize-vector-parcels.mbtiles
Target file:                        rasterize-vector-parcels
Target bitmap size:                 256 x 256
Reading 'rasterize-vector-parcels.mbtiles'
Rasterizing zoom level 14
Source tile count: 23
Creating 'rasterize-vector-parcels'
TypeError: process.stdout.clearLine is not a function
    at printprogress (C:\inetpub\wwwroot\assets\rasterize-vector-tiles-master\printprogress.js:13:18)
    at rasterize (C:\inetpub\wwwroot\assets\rasterize-vector-tiles-master\rasterize-vector-tiles.js:112:5)

I updated to node 10.15.3

**Comment by bjornreppen** [comment]
Removed the clearLine and tested on node 10 which I should have done previous time.

**Comment by hjrobinson** [comment]
Next error:

TypeError: process.stdout.cursorTo is not a function
    at printprogress (C:\inetpub\wwwroot\assets\rasterize-vector-tiles-master\printprogress.js:13:18)
    at rasterize (C:\inetpub\wwwroot\assets\rasterize-vector-tiles-master\rasterize-vector-tiles.js:112:5)

**Comment by hjrobinson** [comment]
Thanks for the prompt corrections! It works now.
